include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for File Transfer
LUCI_DEPENDS:=+luci-compat +luci-lib-jsonc +luci-lib-nixio

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature 